[phases.setup]
nixPkgs = ['...', 'openjdk17']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']

[start]
cmd = 'java -jar target/wanli-backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=staging --server.port=$PORT'

[variables]
SPRING_PROFILES_ACTIVE = 'staging'
DB_SCHEMA = 'staging'
PORT = '8080'
SPRING_DATASOURCE_URL = 'jdbc:postgresql://postgres:UNKAKICITPygEMvfAvzRVYKesMbGoYBz@switchback.proxy.rlwy.net:43164/railway'
SPRING_DATASOURCE_USERNAME = 'postgres'
SPRING_DATASOURCE_PASSWORD = 'UNKAKICITPygEMvfAvzRVYKesMbGoYBz'
CORS_ALLOWED_ORIGINS = 'http://localhost:3000,https://staging.wanli.ai'
JWT_SECRET = 'wanli-staging-secret-key-for-jwt-token-generation-and-validation'