[phases.setup]
nixPkgs = ['...', 'openjdk17']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']

[start]
cmd = 'java -jar target/wanli-backend-0.0.1-SNAPSHOT.jar'

[variables]
SPRING_PROFILES_ACTIVE = 'dev'
DB_SCHEMA = 'public'
PORT = '8080'
DATABASE_URL = 'jdbc:postgresql://localhost:5432/wanli_db'
DB_USERNAME = 'wujames'
DB_PASSWORD = ''
CORS_ALLOWED_ORIGINS = 'http://localhost:3000'
JWT_SECRET = 'mySecretKey123456789012345678901234567890'