[phases.setup]
nixPkgs = ['...', 'openjdk17']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']

[start]
cmd = 'java -jar target/wanli-backend-0.0.1-SNAPSHOT.jar'

[variables]
SPRING_PROFILES_ACTIVE = 'prod'
DB_SCHEMA = 'production'
PORT = '8080'