[phases.setup]
nixPkgs = ['...', 'openjdk17']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']

[start]
cmd = 'java -jar target/wanli-backend-0.0.1-SNAPSHOT.jar'

[variables]
SPRING_PROFILES_ACTIVE = 'prod'
DB_SCHEMA = '${DB_SCHEMA:production}'
PORT = '8080'
DATABASE_URL = '${DATABASE_URL}'
DB_USERNAME = '${DB_USERNAME}'
DB_PASSWORD = '${DB_PASSWORD}'
CORS_ALLOWED_ORIGINS = '${CORS_ALLOWED_ORIGINS:https://wanli.ai}'
JWT_SECRET = '${JWT_SECRET}'