[phases.setup]
nixPkgs = ['...', 'openjdk17']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']

[start]
cmd = 'java -jar target/wanli-backend-0.0.1-SNAPSHOT.jar'

[variables]
SPRING_PROFILES_ACTIVE = 'staging'
DB_SCHEMA = 'staging'
PORT = '8080'
DATABASE_URL = 'postgresql://postgres:UNKAKICITPygEMvfAvzRVYKesMbGoYBz@switchback.proxy.rlwy.net:43164/railway'
DB_USERNAME = 'postgres'
DB_PASSWORD = 'UNKAKICITPygEMvfAvzRVYKesMbGoYBz'
CORS_ALLOWED_ORIGINS = 'http://localhost:3000,https://staging.wanli.ai'
JWT_SECRET = '$JWT_SECRET'