spring:
  datasource:
    url: jdbc:mysql://staging-db-host:3306/wanli_staging?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:wanli_staging}
    password: ${DB_PASSWORD:staging_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

# JWT配置
jwt:
  secret: ${JWT_SECRET:staging-jwt-secret-key-change-in-production}
  expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    root: INFO
    com.wanli: INFO
    org.springframework.security: WARN
  file:
    name: logs/wanli-backend-staging.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized