# 万里后端应用配置文件 - 生产环境
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: wanli-backend
  
  # 数据库配置 - 生产环境
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/wanli_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  # JPA配置 - 生产环境
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境使用validate，不自动创建表
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: ${DB_SCHEMA:production}
  
  # CORS配置 - 生产环境
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://app.wanli.ai}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# 日志配置 - 生产环境
logging:
  level:
    com.wanli.backend: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用信息
info:
  app:
    name: 万里后端系统
    description: 基于Spring Boot的Java后端项目 - 生产环境
    version: 1.0.0
    author: wanli-team
    environment: production

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
