# 本地开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wanli_db
    username: wanli_user
    password: wanli_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Shanghai

# JWT配置
jwt:
  secret: wanli-local-secret-key-for-development-only-2024
  access-token-expiration: 86400000  # 24小时
  refresh-token-expiration: 604800000  # 7天

# 日志配置
logging:
  level:
    com.wanli: debug
    org.springframework.web: debug
    org.springframework.security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/wanli-backend-local.log