# Staging环境配置
spring:
  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: staging

  web:
    cors:
      allowed-origins: https://app.staging.wanli.ai

# 日志配置
logging:
  level:
    com.wanli.backend: INFO
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用信息
info:
  app:
    name: 万里后端系统 - Staging
    description: Staging环境 - 基于Spring Boot的Java后端项目
    version: 1.0.0
    environment: staging
    author: wanli-team