# Production环境配置
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: production

  web:
    cors:
      allowed-origins: https://app.wanli.ai

# 日志配置
logging:
  level:
    com.wanli.backend: WARN
    org.springframework.web: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用信息
info:
  app:
    name: 万里后端系统 - Production
    description: 生产环境 - 基于Spring Boot的Java后端项目
    version: 1.0.0
    environment: production
    author: wanli-team

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized