# Spring Boot 配置文件 - 测试环境
spring:
  # 应用配置
  application:
    name: wanli-backend
  
  # 服务器配置
  server:
    port: ${PORT:9009}
  
  # 数据库配置 - 测试环境 (连接到Railway代理地址)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://switchback.proxy.rlwy.net:43164/railway}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:UNKAKICITPygEMvfAvzRVYKesMbGoYBz}
    driver-class-name: org.postgresql.Driver
    
    # Hikari 连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 测试环境允许自动更新表结构
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${DB_SCHEMA:staging}
  
  # Redis 配置 - 测试环境 (禁用Redis或使用Railway Redis服务)
  data:
    redis:
      enabled: false  # 暂时禁用Redis，避免连接localhost错误
      host: ${REDIS_HOST:redis-staging.up.railway.app}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # 邮件配置 - 测试环境 (使用Railway环境变量)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

# JWT 配置
jwt:
  secret: ${JWT_SECRET:staging-secret-key-change-in-production}
  expiration: ${JWT_EXPIRATION:86400000}  # 24小时

# 日志配置
logging:
  level:
    com.wanli: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/wanli-backend-staging.log
    max-size: 10MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# CORS 配置 - 测试环境
cors:
  allowed-origins: 
    - ${FRONTEND_URL:http://localhost:3000}
    - https://wanli-frontend-staging.up.railway.app
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true