# 万里后端应用配置文件
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: wanli-backend
  
  # 数据库配置
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/wanli_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${DB_SCHEMA:public}
  
  # CORS配置
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  
  # 日志配置
logging:
  level:
    com.wanli.backend: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 应用信息
info:
  app:
    name: 万里后端系统
    description: 基于Spring Boot的Java后端项目
    version: 1.0.0
    author: wanli-team