# Spring Boot 配置文件 - 测试环境
spring:
  profiles:
    active: staging
  
  # 应用配置
  application:
    name: wanli-backend
  
  # 服务器配置
  server:
    port: ${PORT:9009}
  
  # 数据库配置 - 测试环境 (连接到Postgres-WALT服务)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-walt-staging.up.railway.app:5432/railway}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
    # Hikari 连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 测试环境允许自动更新表结构
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis 配置 - 测试环境
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # CORS 配置 - 测试环境
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "https://wanli-frontend-staging.up.railway.app"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

# JWT 配置 - 测试环境
jwt:
  secret: ${JWT_SECRET:staging-secret-key-for-testing-environment-only}
  expiration: 86400000  # 24小时

# 日志配置 - 测试环境
logging:
  level:
    com.wanli: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE