# 万里后端应用配置文件
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: wanli-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    redis:
      enabled: false
  
  # 数据库配置 - 由各环境配置文件覆盖
  datasource:
    driver-class-name: org.postgresql.Driver
  
  # JPA配置 - 由各环境配置文件覆盖
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # CORS配置
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  
# 缓存配置
cache:
  enabled: false  # 缓存开关，测试禁用状态
  type: simple  # 使用简单缓存替代Redis
  default-expire-minutes: 30  # 默认过期时间（分钟）
  max-size: 1000  # 最大缓存大小
  # redis:
  #   time-to-live: 600000

# 日志配置
logging:
  level:
    com.wanli.backend: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"



# 应用信息
info:
  app:
    name: 万里后端系统
    description: 基于Spring Boot的Java后端项目
    version: 1.0.0
    author: wanli-team