# 服务器配置
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# Spring配置
spring:
  application:
    name: wanli-backend
  
  # 数据源配置 - 开发环境
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/wanli_backend_dev}
    username: ${DATABASE_USERNAME:dev_user}
    password: ${DATABASE_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Shanghai
  
  # 多环境配置
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
        
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: NON_NULL

# JWT配置
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForWanliEducationBackendSystem2024}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:7200000}

# 日志配置
logging:
  level:
    com.wanli: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/wanli-backend.log

# 环境标识
app:
  environment: development
  version: ${APP_VERSION:1.0.0-SNAPSHOT}
  railway:
    deployment: false