# 服务器配置
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: wanli-backend
  
  # Redis配置 - 测试环境禁用
  data:
    redis:
      enabled: false
  
  # 数据库配置 - 测试环境
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:UNKAKICITPygEMvfAvzRVYKesMbGoYBz@switchback.proxy.rlwy.net:43164/railway}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:UNKAKICITPygEMvfAvzRVYKesMbGoYBz}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: staging

# JWT配置
jwt:
  secret: ${JWT_SECRET:wanli-staging-secret-key-for-jwt-token-generation-and-validation}
  expiration: 86400000  # 24小时

# CORS配置
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://staging.wanli.ai}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# 日志配置
logging:
  level:
    com.wanli: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 应用信息
info:
  app:
    name: Wanli Backend API
    version: 1.0.0
    environment: staging