# Railway生产环境配置
spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: Asia/Shanghai

# JWT配置
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_EXPIRATION:86400000}  # 默认24小时
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 默认7天

# 服务器配置
server:
  port: ${PORT:8080}

# 日志配置
logging:
  level:
    com.wanli: info
    org.springframework.web: warn
    org.springframework.security: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/wanli-backend-prod.log