# 万里教育后台管理系统 - 测试环境专用配置
spring:
  # 数据库配置 - 测试环境
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/wanli_test}
    username: ${DATABASE_USERNAME:wanli_test}
    password: ${DATABASE_PASSWORD:test123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
  # JPA配置 - 测试环境
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        
# 服务器配置 - 测试环境
server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    
# JWT配置 - 测试环境
jwt:
  secret: ${JWT_SECRET:testSecretKeyForWanliEducationBackendSystemTesting2024}
  expiration: ${JWT_EXPIRATION:86400}
  
# 日志配置 - 测试环境
logging:
  level:
    root: INFO
    com.wanli: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/wanli-backend-test.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    
# 管理端点配置 - 测试环境
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always